apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TysonNemeghaire1/Dev-avec-docker.git
    targetRevision: HEAD
    path: TD-Jour6/k8s
    directory:
      include: '{namespaces,configs}/**/*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
