apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TysonNemeghaire1/Dev-avec-docker.git
    targetRevision: HEAD
    path: TD-Jour6/k8s
    directory:
      recurse: true
      include: '{deployments,services,configs,statefulsets}/**'
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
